<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>CNV_Connect</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Boards\Airbus\A320\Fenix\Overhead.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Boards\Airbus\A320\Fenix\Overhead.json" />
    <EmbeddedResource Include="Boards\Boeing\777\PMDG\Radio.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSUIPCClientDLL" Version="3.3.16" />
    <PackageReference Include="System.IO.Ports" Version="9.0.5" />
  </ItemGroup>

</Project>